---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: default
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgDFpWzYBbYGUwW2eUNckinyfB19MZgBOksxWoHfha8GLFDRVqHnvx6hV4lZeb6gUAnRSpKvFXF2eVyax1tAbjfexRRoZPHPOgMcz/je6WVa47Lxn53fyff4lGfaz+1uxiKqQUDueyqANboC9GJ1n15+uihKeOnOHyibho4lL5c7sXbRKVFDJaNo4jSFZVxsZ63UaYLdkLYKkOcTuKF+wy/awIkzAYSzcB0t2xSdXVELDfU7pCNtw29oYQqmJ/fno4ShW1Jw1gS71C1y5L7AciSaeRoQsPmPZ2T/FzhlnIfzZ5G45HrCy/bX/8+vtUQ71bpBc+kezyiUf+pXc8i0wTmLeHNdvM6Kt2ceeyuW33FX8/k9zPCX85vWOck/IeJARdNkwWXUXBCUL8dZM3r11us0n+GOuuPfOZunuwZKGjPaKyMGOLVKaa3W9ta/HapO8Yj+NI+zKFdB5admemriEfbiIVKvB+Hepsn1l2BmRUfw2KWY1OSBwKRLJBkx4+KiN7y0DCzaTi5wGx3WFY9q9PElnV0FtqWQI5/F5XesBhRLIjau49sTyWbE0Wo5jGRA1Vjfb6uwuh6HRL1GD+hSZcR3rZksSgBMvaSgPVhg8V9Cg23sBN5BZtUe7/tLsadECofXzS1gxmr/ihAHgTuHWsDwioNePQkFPm3qTShSpohSnwryuEusXAYSvClJi/AHUXg/X5PQEF+gxHA8aYOG5u8hGymUUd9Q7nIlylyfWl+TSI7d4CN+ZGkqaPYbmk0S950=
    RABBITMQ_DEFAULT_USER: AgCUiIrm+FXJ2MMd5JRr147Jtq2+giOdzot0MMF4ooe+/svsCAujNBact+BgPdb0thAmdmjCqeveFRkGzFPtAeAfk5Ndqlh7T4/O5hJcl51n2h55OZpU9t5VTsYT64+uLrhgngpsJ7D867EC922RLM+zCKFu7IVU5baTZ2IeIDH1VqCmcB8N7bUVAO0RevtDBmTHqOOUWwYmQFOgDe5Be1Kcv1ieNwH8/FdE1IG49pP2S43knUS7TiNM0CM33ITbey0IQrPDb+tlhniCMctyFTM9ZBEsYGNZCN6f60bGWx6o03p+Lskxxyl2fibMszoInVC0yIonG6NSZLU7j5W9JECw4MHhMHSvQw0UtfIOsisPzaFKTde814p41m2kFkmfFflZoe+wFoGw3rND2rScsxShjH0spdO6742zDTR6KrAcGGLNwBnDHIHh39So4rc7ZcCDjYzkk7Ym5qJl70qyBT6i9Nr2VOlU2sbUx3Cz7xDMFzSZHBHjyeHk1aOtXWb/ceRPbo7++LAqul9tfzgDKt6nBtNho3C6iHLmCQ3tPwrUx0DUMRMIk6YnTBeaIEA6HKkNh70tu8GO5lxx2xKciTF9IY6XLmLoIKZFHh2pJpq1iU2/jsv3X/+hB06mOp5Yvc9oh1XILXcFyMXzZi6u41XVCfbHHVCtINHixEMd4/bqsAq+fUd7Jyn1NuWIUlZ3+39i43BH7/QPjro=
  template:
    metadata:
      name: rabbitmq-secret
      namespace: default
    type: Opaque
